# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end


  lane :beta do
    # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )

    # ...
  end


  desc "My awesome app"
      lane :distribute do
      gradle(
        task: "assemble",
        build_type: "Release"
      )
         release = firebase_app_distribution(
              app: "1:105016839252:android:6ba0a500fc437da462b1c1",
              testers: "tandelmehul97@gmail.com",
              release_notes: "Latest build with cover image"

          )
      end

      desc 'GitHub actions release'
      lane :version do |options|
        updateVersion(options)
      end


      lane :github do |_options|
        gradle(task: 'clean bundleRelease')
        upload_to_play_store(
          skip_upload_metadata: true,
          skip_upload_changelogs: true,
          skip_upload_screenshots: true,
          skip_upload_images: true,
          skip_upload_apk: true,
          json_key_data: ENV['GOOGLE_PLAY_AUTH']
        )
      end
end
