name: Distribute

on:
  push:
    branches: [ test ]

jobs:
  distribute:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1

          
          - name: Distribute app with App Distribution 
        run: bundle exec fastlane distribute
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
