name: Test React Native Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
          sudo gem install fastlane -NV
          bundle exec gem install fastlane

      - name: Run Your Script
        run: bundle exec fastlane distribute

