name: Distribute

on:
  push:
    branches: [ test ]

jobs:
  distribute:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
